# REAL: Replace with MySQL announcements table

WEAVE_INTERFACES = [
    {"id": 0, "ui_title": "Docusign eSign", "ui_name": "ConnectHomeEmbedDocusignWindow", "weave_function": "GWMConnectHomeView", "seal_id": "103845"},
    {"id": 1, "ui_title": "Conversations", "ui_name": "ConversationsMainWindow", "weave_function": "GWMConnectCallMemoRead", "seal_id": "90176"},
    {"id": 2, "ui_title": "EML/PLC Dashboard", "ui_name": "CreditConnect-GCM-EMLPLCDashboard", "weave_function": "GWMConnectCollateralMonitoringView", "seal_id": "90083"},
    {"id": 3, "ui_title": "EML Rule Maintenance", "ui_name": "CreditConnect-EML-Rule-Maintenance", "weave_function": "GWMConnectCollateralMonitoringView", "seal_id": "90083"},
    {"id": 4, "ui_title": "OnboardingConnectKycComp...", "ui_name": "OnboardingConnectKycComparisonManager", "weave_function": "OnboardingConnectLaunch", "seal_id": "84874"},
]

ANNOUNCEMENTS = [
    {
        "id": 5, "title": "Advisor Connect — Degraded Performance in EMEA",
        "status": "ongoing", "severity": "major",
        "impacted_apps": ["Advisor Connect (90176)"],
        "start_time": "2026-02-26 06:30 UTC", "end_time": "",
        "description": "Advisor Connect is experiencing elevated latency and intermittent timeouts for EMEA users. The platform team is actively investigating the root cause.",
        "latest_updates": "06:45 UTC — Identified database connection pool exhaustion in FRA region. Scaling operations in progress.",
        "incident_number": "INC-2026-0412",
        "impact_type": "Performance", "impact_description": "Users may experience slow page loads and occasional 504 errors.",
        "header_message": "Degraded performance impacting EMEA clients",
        "email_recipients": ["emea-ops@jpmchase.com", "connect-oncall@jpmchase.com"],
        "category": "Infrastructure", "region": "EMEA",
        "next_steps": "Database team scaling connection pools; ETA 30 min.",
        "help_info": "Contact the Connect Operations Center at ext. 4-7890",
        "email_body": "<p>Advisor Connect is currently experiencing degraded performance in the EMEA region.</p>",
        "channels": {"teams": True, "email": True, "connect": True, "banner": True},
        "pinned": True,
        "teams_channels": ["#connect-incidents", "#emea-operations"],
        "email_source": "Technology",
        "email_hide_status": False,
        "connect_dont_send_notification": False,
        "connect_banner_position": "in_ui",
        "connect_target_entities": ["FRA-PB", "LON-PB"],
        "connect_target_regions": ["EMEA"],
        "connect_weave_interfaces": [1],
        "ann_status": "open", "author": "J. Martinez",
        "date": "2026-02-26 06:30 UTC",
    },
    {
        "id": 4, "title": "Spectrum Portfolio Mgmt — Scheduled Maintenance Window",
        "status": "ongoing", "severity": "standard",
        "impacted_apps": ["Spectrum Portfolio Mgmt (90215)"],
        "start_time": "2026-02-27 02:00 UTC", "end_time": "2026-02-27 06:00 UTC",
        "description": "Scheduled maintenance for Spectrum Portfolio Management. The system will be unavailable during the maintenance window for database migration.",
        "latest_updates": "",
        "incident_number": "CHG-2026-1188",
        "impact_type": "Availability", "impact_description": "Full outage during maintenance window. Read-only mode 30 min before.",
        "header_message": "Planned downtime — Spectrum Portfolio Mgmt",
        "email_recipients": ["spectrum-users@jpmchase.com"],
        "category": "Maintenance", "region": "Global",
        "next_steps": "No action required. System will auto-recover after maintenance.",
        "help_info": "Reach out to Spectrum Support on ServiceNow",
        "email_body": "",
        "channels": {"teams": True, "email": True, "connect": False, "banner": True},
        "pinned": False,
        "teams_channels": ["#spectrum-announcements"],
        "email_source": "Operations",
        "email_hide_status": False,
        "connect_dont_send_notification": False,
        "connect_banner_position": "in_ui",
        "connect_target_entities": [],
        "connect_target_regions": [],
        "connect_weave_interfaces": [],
        "ann_status": "open", "author": "S. Patel",
        "date": "2026-02-25 14:00 UTC",
    },
    {
        "id": 3, "title": "Connect OS — New KYC Comparison Tool Rollout",
        "status": "resolved", "severity": "none",
        "impacted_apps": ["Connect OS (88180)"],
        "start_time": "2026-02-24 09:00 UTC", "end_time": "2026-02-24 09:00 UTC",
        "description": "New KYC Comparison Manager interface is now available in Connect OS for all regions. This release includes enhanced document matching and automated compliance checks.",
        "latest_updates": "Rollout complete to all regions.",
        "incident_number": "",
        "impact_type": "Enhancement", "impact_description": "No negative impact. New feature availability.",
        "header_message": "",
        "email_recipients": [],
        "category": "Release", "region": "Global",
        "next_steps": "Training materials available on the internal wiki.",
        "help_info": "",
        "email_body": "",
        "channels": {"teams": False, "email": False, "connect": True, "banner": False},
        "pinned": False,
        "teams_channels": [],
        "email_source": "",
        "email_hide_status": False,
        "connect_dont_send_notification": True,
        "connect_banner_position": "in_ui",
        "connect_target_entities": ["USA-PB", "USA-JPMS", "LON-PB"],
        "connect_target_regions": ["NA", "EMEA"],
        "connect_weave_interfaces": [4],
        "ann_status": "open", "author": "R. Chen",
        "date": "2026-02-24 09:00 UTC",
    },
    {
        "id": 2, "title": "EML Rule Maintenance — Collateral Monitoring Update",
        "status": "resolved", "severity": "standard",
        "impacted_apps": ["Advisor Connect (90176)"],
        "start_time": "2026-02-23 18:00 UTC", "end_time": "2026-02-23 20:15 UTC",
        "description": "Emergency update applied to EML rule engine to correct margin call calculation logic for APAC collateral pools.",
        "latest_updates": "20:15 UTC — Patch deployed and verified. All margin calculations confirmed accurate.",
        "incident_number": "INC-2026-0398",
        "impact_type": "Data Integrity", "impact_description": "Incorrect margin call values for APAC collateral during affected period.",
        "header_message": "EML rule engine patched",
        "email_recipients": ["credit-ops@jpmchase.com", "apac-risk@jpmchase.com"],
        "category": "Incident", "region": "APAC",
        "next_steps": "Post-incident review scheduled for Feb 28.",
        "help_info": "Contact Credit Risk Operations for reconciliation queries",
        "email_body": "<p>An emergency patch was applied to the EML rule engine.</p>",
        "channels": {"teams": True, "email": True, "connect": False, "banner": False},
        "pinned": False,
        "teams_channels": ["#credit-incidents", "#apac-operations"],
        "email_source": "Risk Management",
        "email_hide_status": False,
        "connect_dont_send_notification": False,
        "connect_banner_position": "in_ui",
        "connect_target_entities": [],
        "connect_target_regions": [],
        "connect_weave_interfaces": [],
        "ann_status": "open", "author": "A. Nakamura",
        "date": "2026-02-23 18:00 UTC",
    },
    {
        "id": 1, "title": "DocuSign eSign — Certificate Renewal Complete",
        "status": "closed", "severity": "none",
        "impacted_apps": [],
        "start_time": "2026-02-20 12:00 UTC", "end_time": "2026-02-20 12:30 UTC",
        "description": "SSL/TLS certificate renewal for DocuSign eSign integration endpoints completed successfully. No user impact was observed.",
        "latest_updates": "Certificates renewed. Monitoring confirmed no errors.",
        "incident_number": "CHG-2026-1145",
        "impact_type": "Security", "impact_description": "None — proactive renewal.",
        "header_message": "",
        "email_recipients": [],
        "category": "Maintenance", "region": "Global",
        "next_steps": "Next renewal scheduled for Aug 2026.",
        "help_info": "",
        "email_body": "",
        "channels": {"teams": False, "email": False, "connect": False, "banner": True},
        "pinned": False,
        "teams_channels": [],
        "email_source": "",
        "email_hide_status": False,
        "connect_dont_send_notification": False,
        "connect_banner_position": "in_ui",
        "connect_target_entities": [],
        "connect_target_regions": [],
        "connect_weave_interfaces": [],
        "ann_status": "closed", "author": "M. Williams",
        "date": "2026-02-20 12:00 UTC",
    },
]
_next_announcement_id = 6
